driver:
  # Driver info defined in .kitchen.local.yml.*
  
provisioner:
  name: chef_zero
  require_chef_omnibus: 12.17.44

platforms:
  - name: ubuntu-14.04
    run_list: apt::default
    driver_config:
      # For AWS driver
      image_id: ami-bb156ad1 # 14.04.4 https://cloud-images.ubuntu.com/locator/ec2/
      tags:
        Name: ansible-dk-build-ubuntu-14.04-<%= ENV['USER'] %>
      # For Docker
      image: ubuntu-chef-12.16
      platform: ubuntu
      
  - name: centos-72
    run_list: yum-epel::default
    driver_config:
      # For AWS driver
      image_id: ami-6d1c2007 # Official CentOS 7.2 with updates - from AWS Marketplace.
      tags:
        Name: ansible-dk-build-centos-7.2-<%= ENV['USER'] %>
      # For Docker driver
      image: centos-chef-12.17:7
      # For Vagrant driver 
      box: bento/centos-7.2

transport:
  connection_timeout: 30

suites:
  - name: default
    run_list:
      - omnibus::default                     # Installs omnibus and the build toolchain
      - ansible-dk-builder::default          # Executes the build
    attributes:
      omnibus:
        install_dir:         /opt/ansible-dk
        project_repo:        /var/cache/omnibus-project
