driver:
  name: ec2
  # availability_zone: ADD THIS IN .kitchen.local.yml
  # aws_ssh_key_id: ADD THIS IN .kitchen.local.yml
  instance_type: m3.large
  # security_group_ids: ADD THIS IN .kitchen.local.yml
  interface: private
  # shared_credentials_profile: ADD THIS IN .kitchen.local.yml
  # subnet_id: ADD THIS IN .kitchen.local.yml
  tags:
    project: labs-ansible-dk
    type: build-slave
    engineer: <%= ENV['USER'] %>
  
provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1

platforms:
  - name: ubuntu-14.04
    run_list: apt::default
    driver:
      image_id: ami-bb156ad1 # 14.04.4 https://cloud-images.ubuntu.com/locator/ec2/
      tags:
        Name: ansible-dk-build-ubuntu-14.04-<%= ENV['USER'] %>

transport:
  # ssh_key: ADD THIS IN .kitchen.local.yml
  connection_timeout: 30
        
suites:
  - name: default
    run_list:
      - omnibus::default                     # Installs omnibus and the build toolchain
      - ansible-dk-builder::default          # Executes the build
    attributes:
      omnibus:
        build_user:          vagrant
        build_user_group:    vagrant
        build_user_password: vagrant
        install_dir:         /opt/ansible-dk
