---
- hosts: localhost
  connection: local
  vars:
    role_name: example
    role_path: "."
    role_subdirectories:
      - tasks
      - handlers
      - templates
      - files
      - vars
      - meta
  tasks:

  - name: create top level role directory
    file: state=directory path="{{ role_path }}/{{ role_name }}" recurse=yes

  - name: create subdirectories
    file: state=directory path="{{ role_path }}/{{ role_name }}/{{ item }}"
    with_items: "{{ role_subdirectories }}"

  - name: create main.yml files
    copy: content="---\n" dest="{{ role_path }}/{{ role_name }}/{{ item }}/main.yml"
    with_items: "{{ role_subdirectories }}"
